name: build-picow

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Toolchain info
        run: |
          uname -a
          cmake --version
          arm-none-eabi-gcc --version || true

      - name: Install toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake gcc-arm-none-eabi libnewlib-arm-none-eabi

      - name: Clone MicroPython and build mpy-cross
        run: |
          git clone --recurse-submodules https://github.com/micropython/micropython.git
          make -C micropython/mpy-cross

      - name: Resolve USER_C_MODULES path (root-level micropython.cmake)
        run: |
          set -e
          UCM=$(realpath "${GITHUB_WORKSPACE}/micropython.cmake")
          echo "USER_C_MODULES => ${UCM}"
          [ -f "${UCM}" ] || (echo "::error file=micropython.cmake::micropython.cmake not found at ${UCM}"; exit 1)
          echo "UCM=${UCM}" >> $GITHUB_ENV

      - name: Build Pico W firmware (rp2) with verbose logs and no -Werror
        run: |
          set -e
          make -C micropython/ports/rp2 BOARD=RPI_PICO_W clean
          make -C micropython/ports/rp2 BOARD=RPI_PICO_W submodules
          # V=1 -> verbose CMake/make; WERROR=0 -> غیرفعال کردن -Werror برای کل بیلد
          make -C micropython/ports/rp2 -j BOARD=RPI_PICO_W USER_C_MODULES="${UCM}" V=1 WERROR=0

      - name: Upload UF2 artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware-RPI_PICO_W
          path: micropython/ports/rp2/build-RPI_PICO_W/firmware.uf2
